import Head from "next/head"


export default function Blog(props) {
    return (
    <main>
      <Head>
        <title>My Next App | Post 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <article itemscope itemtype="https://schema.org/Article">
        <header>
            <h1 itemprop="name">{props.title}</h1>
            <p itemprop="datePublished">{props.date}</p>
            <p>
            by <span itemprop="author">{props.author}</span>
            </p>
        </header>

        <div itemprop="articleBody">{props.children}</div>
      </article>

      <form method="POST" action="/api/comments" onSubmit={(e) => e.preventDefault()}> 
        <input name='name' type="text" /><br />
        <textarea rows="2" name='content'></textarea> <br />
        <input type="submit" value="Submit" />
      </form>
    </main>
  )
}
