import Head from "next/head";
import { useState, useEffect } from "react";

export default function Blog(props) {
  const [comments, setComments] = useState([]);

  async function submitForm(e) {
    e.preventDefault();
    const body = JSON.stringify({
      name: e.target.name.value,
      content: e.target.content.value,
    });
    const data = await (
      await fetch("/api/comments", {
        method: "POST",
        body,
      })
    ).json();

    // Update comments on the page
    setComments([...comments, data]);
  }

  useEffect(() => {
    // Happens on page load
    async function loadComments() {
      const data = await (
        await fetch("/api/comments", { method: "GET" })
      ).json();
      setComments(data);
    }

    loadComments();
  }, []);

  return (
    <main>
      <Head>
        <title>My Next App | Post 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <article itemScope itemType="https://schema.org/Article">
        <header>
          <h1 itemProp="name">{props.title}</h1>
          <p itemProp="datePublished">{props.date}</p>
          <p>
            by <span itemProp="author">{props.author}</span>
          </p>
        </header>

        <div itemProp="articleBody">{props.children}</div>
      </article>

      <h3>Comments</h3>
      <form method="POST" onSubmit={submitForm}>
        <input name="name" type="text" id="name" placeholder="Name (opt.)" />
        <br />
        <textarea
          rows="2"
          name="content"
          id="content"
          placeholder="Comment"
          required={true}
        ></textarea>
        <br />
        <input type="submit" value="Submit" />
      </form>

      <ul>
        {comments.map((c, i) => (
          <li key={i}>
            <h4>{c.name}</h4>
            <p>{c.content}</p>
          </li>
        ))}
      </ul>
    </main>
  );
}
